### PR TITLE
Added first pass at twitch 

### PR DESCRIPTION
**Pull request by MosesTroyer**
Adds the twitch page. All it has is the twitch stream, also changed the css to accommodate it.

### CODE REVIEW

**Comment by dyladan** [comment]
this looks mostly good but i'm wondering about https://github.com/ccowmu/whatistheplan.com/pull/28/files#diff-0515afef44d2fd6aa5703fbbe27377e4R52 where you set width 100% and height 56.25%.
1. Why is the height such a specific number? makes me think you were developing for your screen without thinking of others.
2. Why is the width and height not the same as in the iframe where you set it as height="378" width="620"?

good job on the test by the way

**Comment by MosesTroyer** [comment]
The width and height are set so that the stream is the proper size (16 / 9). Without it, the stream gets very elongated, iirc

**Comment by dyladan** [comment]
but 100% and 56.25% is not always the same ratio. on different screens that isn't 16x9

**Comment by MosesTroyer** [comment]
Hm, guess I didn’t really think about that. The twitch stream link tries to set the amount of pixels for width and height, but it didn’t work for me.

**Comment by dyladan** [comment]
i'll take a looksie later. there's probably an easy way to do it. If nothing else we can hardcode max-height and max-width then use media queries to scale down on smaller screens

**Comment by chrissphinx** [comment]
this actually got merged idk why it doesn't know that

**Pull request closed without merging**
